export enum Right {
  ADMIN_USER_CREATE_USER_GROUP = '1',
  ADMIN_USER_SINGUP_VENUE_USER = '2',
  ADMIN_USER_CREATE_MENU = '3',
  ADMIN_USER_GET_MENUS = '4',
  ADMIN_USER_GET_UPLOAD_MAP = '5',
  ADMIN_USER_GET_MAPS_PER_MENU = '6',

  VENUE_USER_ADD_STAFF = '100',
  VENUE_USER_CREATE_MENU = '101',
  VENUE_USER_CREATE_ITEM = '102',
  VENUE_USER_CREATE_MENU_ITEM = '102',
  VENUE_USER_UPDATE_ITEM = '103',
  VENUE_USER_GET_ITEMS = '103',
}
